### ISSUE TITLE
Doomgrader dotnet 2705 abort

### ISSUE THREAD

**Issue by brandflake11** [lpww/doomgrader#1]
Hello,
I run the script and the depotdownloader has a problem with dotnet for some reason. Here is the output of the script:
```
/run/media/nvme/.doomgrader/depotdownloader /run/media/nvme/.doomgrader/doomgrader
--2020-05-17 22:40:53--  https://github.com/SteamRE/DepotDownloader/releases/download/DepotDownloader_2.3.4/depotdownloader-2.3.4.zip

Saving to: ‘depotdownloader_2.3.4.zip’

depotdownloader_2.3 100%[===================>]   2.10M  10.5MB/s    in 0.2s    

2020-05-17 22:40:54 (10.5 MB/s) - ‘depotdownloader_2.3.4.zip’ saved [2201394/2201394]

depotdownloader_2.3 100%[===================>]   2.10M  10.5MB/s    in 0.2s    

2020-05-17 22:40:54 (10.5 MB/s) - ‘depotdownloader_2.3.4.zip’ saved [2201394/2201394]

Archive:  depotdownloader_2.3.4.zip
replace depotdownloader? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
 extracting: depotdownloader         
 extracting: depotdownloader.bat     
  inflating: DepotDownloader.deps.json  
  inflating: DepotDownloader.dll     
  inflating: DepotDownloader.dll.config  
  inflating: DepotDownloader.pdb     
  inflating: DepotDownloader.runtimeconfig.json  
  inflating: LICENSE                 
  inflating: protobuf-net.dll        
  inflating: README.md               
  inflating: SteamKit2.dll           
  inflating: SteamKit2.pdb           
  inflating: System.Reflection.DispatchProxy.dll  
  inflating: System.Security.Principal.Windows.dll  
  inflating: System.ServiceModel.dll  
  inflating: System.ServiceModel.Primitives.dll  
Connecting to Steam3... Done!
Logging '' into Steam3...Unhandled exception. System.ArgumentException: LogOn requires a username and password to be set in 'details'.
   at SteamKit2.SteamUser.LogOn(LogOnDetails details) in C:\Projects\SteamKit\SteamKit2\SteamKit2\Steam\Handlers\SteamUser\SteamUser.cs:line 299
   at DepotDownloader.Steam3Session.ConnectedCallback(ConnectedCallback connected) in C:\Projects\DepotDownloader\DepotDownloader\Steam3Session.cs:line 504
   at SteamKit2.Internal.Callback`1.Run(Object callback) in C:\Projects\SteamKit\SteamKit2\SteamKit2\Steam\SteamClient\CallbackMgr\CallbackMgr_Internals.cs:line 81
   at SteamKit2.CallbackManager.<>c__DisplayClass10_0.<Handle>b__1(CallbackBase callback) in C:\Projects\SteamKit\SteamKit2\SteamKit2\Steam\SteamClient\CallbackMgr\CallbackMgr.cs:line 142
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at SteamKit2.CallbackManager.Handle(ICallbackMsg call) in C:\Projects\SteamKit\SteamKit2\SteamKit2\Steam\SteamClient\CallbackMgr\CallbackMgr.cs:line 143
   at SteamKit2.CallbackManager.RunWaitCallbacks(TimeSpan timeout) in C:\Projects\SteamKit\SteamKit2\SteamKit2\Steam\SteamClient\CallbackMgr\CallbackMgr.cs:line 71
   at DepotDownloader.Steam3Session.WaitForCallbacks() in C:\Projects\DepotDownloader\DepotDownloader\Steam3Session.cs:line 478
   at DepotDownloader.Steam3Session.WaitUntilCallback(Action submitter, WaitCondition waiter) in C:\Projects\DepotDownloader\DepotDownloader\Steam3Session.cs:line 141
   at DepotDownloader.Steam3Session.WaitForCredentials() in C:\Projects\DepotDownloader\DepotDownloader\Steam3Session.cs:line 154
   at DepotDownloader.ContentDownloader.InitializeSteam3(String username, String password) in C:\Projects\DepotDownloader\DepotDownloader\ContentDownloader.cs:line 356
   at DepotDownloader.Program.MainAsync(String[] args) in C:\Projects\DepotDownloader\DepotDownloader\Program.cs:line 196
   at DepotDownloader.Program.Main(String[] args) in C:\Projects\DepotDownloader\DepotDownloader\Program.cs:line 14
./depotdownloader: line 1:  2705 Aborted                 (core dumped) dotnet DepotDownloader.dll "$@"
me: A
 extracting: depotdownloader         
 extracting: depotdownloader.bat     
  inflating: DepotDownloader.deps.json  
  inflating: DepotDownloader.dll     
  inflating: DepotDownloader.dll.config  
  inflating: DepotDownloader.pdb     
  inflating: DepotDownloader.runtimeconfig.json  
  inflating: LICENSE                 
  inflating: protobuf-net.dll        
  inflating: README.md               
  inflating: SteamKit2.dll           
  inflating: SteamKit2.pdb           
  inflating: System.Reflection.DispatchProxy.dll  
  inflating: System.Security.Principal.Windows.dll  
  inflating: System.ServiceModel.dll  
  inflating: System.ServiceModel.Primitives.dll  
Connecting to Steam3... Done!
Logging '' into Steam3...Unhandled exception. System.ArgumentException: LogOn requires a username and password to be set in 'details'.
   at SteamKit2.SteamUser.LogOn(LogOnDetails details) in C:\Projects\SteamKit\SteamKit2\SteamKit2\Steam\Handlers\SteamUser\SteamUser.cs:line 299
   at DepotDownloader.Steam3Session.ConnectedCallback(ConnectedCallback connected) in C:\Projects\DepotDownloader\DepotDownloader\Steam3Session.cs:line 504
   at SteamKit2.Internal.Callback`1.Run(Object callback) in C:\Projects\SteamKit\SteamKit2\SteamKit2\Steam\SteamClient\CallbackMgr\CallbackMgr_Internals.cs:line 81
   at SteamKit2.CallbackManager.<>c__DisplayClass10_0.<Handle>b__1(CallbackBase callback) in C:\Projects\SteamKit\SteamKit2\SteamKit2\Steam\SteamClient\CallbackMgr\CallbackMgr.cs:line 142
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at SteamKit2.CallbackManager.Handle(ICallbackMsg call) in C:\Projects\SteamKit\SteamKit2\SteamKit2\Steam\SteamClient\CallbackMgr\CallbackMgr.cs:line 143
   at SteamKit2.CallbackManager.RunWaitCallbacks(TimeSpan timeout) in C:\Projects\SteamKit\SteamKit2\SteamKit2\Steam\SteamClient\CallbackMgr\CallbackMgr.cs:line 71
   at DepotDownloader.Steam3Session.WaitForCallbacks() in C:\Projects\DepotDownloader\DepotDownloader\Steam3Session.cs:line 478
   at DepotDownloader.Steam3Session.WaitUntilCallback(Action submitter, WaitCondition waiter) in C:\Projects\DepotDownloader\DepotDownloader\Steam3Session.cs:line 141
   at DepotDownloader.Steam3Session.WaitForCredentials() in C:\Projects\DepotDownloader\DepotDownloader\Steam3Session.cs:line 154
   at DepotDownloader.ContentDownloader.InitializeSteam3(String username, String password) in C:\Projects\DepotDownloader\DepotDownloader\ContentDownloader.cs:line 356
   at DepotDownloader.Program.MainAsync(String[] args) in C:\Projects\DepotDownloader\DepotDownloader\Program.cs:line 196
   at DepotDownloader.Program.Main(String[] args) in C:\Projects\DepotDownloader\DepotDownloader\Program.cs:line 14
./depotdownloader: line 1:  2705 Aborted                 (core dumped) dotnet DepotDownloader.dll "$@"
```
What could be the issue with this? I think I set up the variables in the script right!
Thank you very much for your time!

EDIT: By looking at the output above, it looked like the username was not input into a variable. After further bash learning, the two read lines need this to them (lines 15-16):

```
read -p "Enter your Steam username:" STEAM_USERNAME
read -s -p "Enter your Steam password:" STEAM_PASSWORD
```

EDIT 2:
I am silly, I deleted the STEAM_USERNAME and STEAM_PASSWORD keywords, which is why it didn't work for me. You do not have to fill in your credentials on these lines, keep these variable names intact and the script will simply ask you for your credentials!

**Comment by lpww** [comment]
@brandflake11 I'm glad you got it working! Let me know if you get the game running :)

**Comment by brandflake11** [comment]
@lpww Thank you so much for this script. The script worked! I am never deleting these files of the older working-on-linux version of Doom Eternal.

**Comment by lpww** [comment]
Great news! Rip and tear baby
